baseurl = "https://muryp.my.id/"
title = "MuryP"
theme = "muryp"

googleAnalytics = "UA-code"
disqusShortname = "muryp"

[taxonomies]
  category = "categories"
  tag = "tags"
  halo = "halo"

[permalinks]
  blog = "/:slug/"
  pages = "/:slug/"

[params]
    # Site Author
    author = "MuryP"

    # Description/subtitle for homepage
    description = "MuryP, MuryP Beta, Internet, Technology, hardware, Operating Sistem, Software, Jaringan Komunikasi, JarKom, TIK, Ringkasan, Alief Prihantoro, Alif MuryP, Buku, Ebook,My Project Drawing/Desain,UI/UX,front end,Blogging, SEO,catatan"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]