baseurl = "https://muryp.my.id/"
title = "MuryP"
theme = "muryp"

googleAnalytics = "G-4XH6NY1N24"
disqusShortname = "muryp"

[outputs]
    home = ["HTML", "RSS", "JSON"]
    blog = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  catatan = "catatan"
  learn = "learn"
  author = "authors"

[permalinks]
  blog = "/:slug/"
  laman = "/:slug/"
  en = "/en/:slug/"

languageCode = "en-us"
DefaultContentLanguage = "en"
paginate = 12

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  github = "https://github.com/alifmuryp"
  gitlab = "https://gitlab.com/muryp"
  facebook = "https://facebook.com/alifmuryp"
  og_image = "/images/noimg.png"
  sitename = "MuryP Beta"
  twitter = "@alifmuryp"
    # Site Author
    author = "MuryP"
    # Description/subtitle for homepage
    description = "MuryP, MuryP Beta, Internet, Technology, hardware, Operating Sistem, Software, Jaringan Komunikasi, JarKom, TIK, Ringkasan, Alief Prihantoro, Alif MuryP, Buku, Ebook,My Project Drawing/Desain,UI/UX,front end,Blogging, SEO,catatan"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]