baseurl = "https://www.ardianta.com"
title = "MuryP | Front End"
theme = "murypStudio"

googleAnalytics = "UA-54154424-1"
disqusShortname = "alifmuryp"

[permalinks]
  post = "/blog/:slug/"
  page = "/:slug/"

[params]
    # Site Author
    author = "MuryP"

    # Description/subtitle for homepage
    description = "MuryP, MuryP Studio, Internet, Technology, hardware, Operating Sistem, Software, Jaringan Komunikasi, JarKom, TIK, Ringkasan, Alief Prihantoro, Alif MuryP, Buku, Ebook,My Project Drawing/Desain,UI/UX,front end,Blogging, SEO"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    wight = 1
  [[menu.main]]
    identifier = "art"
    name = "Art"
    url = "https://ardiantapargo.deviantart.com/"
    wight = 2
  [[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ardiantapargo"
    wight = 3
  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/ardianta"
    wight = 4
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "http://feeds.feedburner.com/ardianta"
    wight = 5