[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
  
[build]
  publish = "public"
  command = "hugo --minify"

[context.production]
  command = "hugo --minify"
  [context.production.environment]
    HUGO_VERSION = "0.80.0"
    HUGO_ENV = "production"